POST http://localhost:8000/login
Content-Type: application/json

{"username": "test_user2", "password": "test123"}


# install plugin before usage (rest client)

###
POST http://localhost:8000/signup
Content-Type: application/json

{ "username": "test_user2", "password": "test123", "email": "test1@test.com" }

###

POST http://localhost:8000/test_token
Content-Type: application/json

{}